align <- function(index,readfile1,readfile2=NULL,input_format="FASTQ",output_file,output_format="SAM",nsubreads=10,TH1=3,TH2=1,nthreads=1,indels=5,phredOffset=33,tieBreakQS=FALSE,tieBreakHamming=FALSE,unique=FALSE,nBestLocations=1,minFragLength=50,maxFragLength=600,PE_orientation="fr",nTrim5=0,nTrim3=0,readGroupID=NULL,readGroup=NULL,color2base=FALSE,DP_GapOpenPenalty=-2,DP_GapExtPenalty=0,DP_MismatchPenalty=0,DP_MatchScore=2,reportFusions=FALSE)
{
	opt <- paste("-i",index,"-r",readfile1,sep=",")
	if(!is.null(readfile2)) 
		opt <- paste(opt,"-R",readfile2,sep=",")
	if(tolower(input_format) == "sam")
		opt <- paste(opt,"--SAMinput",sep=",")
	if(tolower(input_format) == "bam")
		opt <- paste(opt,"--BAMinput",sep=",")
	opt <- paste(opt,"-o",output_file,sep=",")	
	if(tolower(output_format) == "bam")
		opt <- paste(opt,"--BAMoutput",sep=",")	  
	opt <- paste(opt,"-n",nsubreads,"-m",TH1,"-p",TH2,"-T",nthreads,"-I",indels,sep=",")
	if(tieBreakQS)
		opt <- paste(opt,"-Q",sep=",")
	if(tieBreakHamming)
		opt <- paste(opt,"-H",sep=",")
	if(unique)
		opt <- paste(opt,"-u",sep=",")
	opt <- paste(opt,"-B",nBestLocations,"-d",minFragLength,"-D",maxFragLength,"-S",PE_orientation,"--trim5",nTrim5,"--trim3",nTrim3,sep=",")
	if(!is.null(readGroupID))
	  opt <- paste(opt,"--rg-id",readGroupID,sep=",")
	if(!is.null(readGroup))
	  opt <- paste(opt,"--rg",readGroup,sep=",")
	if(color2base)
		opt <- paste(opt,"-b",sep=",")
	opt <- paste(opt,"-G",DP_GapOpenPenalty,"-E",DP_GapExtPenalty,"-X",DP_MismatchPenalty,"-Y",DP_MatchScore,sep=",")
	if(reportFusions)
		opt <- paste(opt,"--reportFusions",sep=",")
	if(phredOffset == 33)
		opt <- paste(opt,"-P",3,sep=",")
	else
		opt <- paste(opt,"-P",6,sep=",")

	cmd <- paste("subread-align",opt,sep=",")
	n <- length(unlist(strsplit(cmd,",")))
	C_args <- .C("R_align_wrapper",as.integer(n),as.character(cmd),PACKAGE="Rsubread")
}
